apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ExternalName
  externalName: voting-redis-master.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ExternalName
  externalName: voting-db-rw.default.svc.cluster.local
