apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result
          image: dockersamples/examplevotingapp_result:before
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_HOST
              value: "voting-db-rw" # Direct Service Name
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "appuser"
            - name: POSTGRES_DB
              value: "app"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voting-db-app-user
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: result
