apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: dockersamples/examplevotingapp_worker
          env:
            - name: REDIS_HOST
              value: "voting-redis-master" # Direct Service Name
            - name: POSTGRES_HOST
              value: "voting-db-rw" # Direct Service Name
            - name: POSTGRES_USER
              value: "appuser"
            - name: POSTGRES_DB
              value: "app"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voting-db-app-user
                  key: password
