apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: dockersamples/examplevotingapp_worker
          env:
            - name: POSTGRES_HOST
              value: "db"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "appuser" # <--- MUST MATCH DB USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: voting-db-app-user
                  key: password
            - name: POSTGRES_DB # <--- NEW: Force app to use 'app' DB
              value: "app"
